---
- name: Deploy latest version of Cilium chart inside kube-system namespace
  kubernetes.core.helm:
    name: cilium
    chart_ref: oci://quay.io/cilium/charts/cilium
    release_namespace: kube-system
    create_namespace: true
    wait: true
    wait_timeout: 15m
    values:
      version: 1.19.2
      kubeProxyReplacement: true
      k8sServiceHost: "{{ ansible_facts['eth1']['ipv4']['address'] | default(ansible_facts['eth0']['ipv4']['address']) }}"
      k8sServicePort: 6443
      hubble:
        enabled: true
        ui:
          enabled: true
        relay:
          enabled: true
        tls:
          auto:
            enabled: true
            method: cronJob
      certgen:
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
            operator: Exists
