---

- name: Configure base settings on all hosts
  hosts: all
  any_errors_fatal: true
  roles:
    - "10-configure-base"

- name: Initialize the cluster
  hosts: controlplane[0]
  any_errors_fatal: true
  roles:
    - "15-init-controlplane"
  vars:
    schedulable: true

- name: Join nodes to the cluster
  hosts: all
  any_errors_fatal: true
  roles:
    - "20-join-workers"
  vars:
    join_command: "{{ hostvars[groups['controlplane'][0]]['join_command_output'].stdout }}"
    certificate_key: "{{ hostvars[groups['controlplane'][0]]['certificate_key_output'].stdout_lines[-1] }}"

- name: Install monitoring tools
  hosts: controlplane[0]
  gather_facts: true
  roles:
    - "25-monitoring"
  vars:
    monitor_stack_state: absent
