---

- hosts: all
  roles:
    - "10-configure-base"

- name: Add kubeadm init config to control planes
  hosts: controlplane
  gather_facts: false
  tasks:
    - name: Use template module to deploy config
      ansible.builtin.template:
        src: templates/kubeadm-config-init.yml.j2
        dest: /home/ubuntu/kubeadm-config.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

- hosts: controlplane[0]
  tasks:
    - block:
      - name: initialize kubernetes with the necessary args
        ansible.builtin.command:
          argv:
            - kubeadm
            - init
            - --config=/home/ubuntu/kubeadm-config.yaml
            - --upload-certs
          creates: /etc/kubernetes/admin.conf
        become: true
        register: k8s_init_output

      - name: copy kube config into ubuntu's home dir subfolder
        ansible.builtin.copy:
          remote_src: yes
          src: /etc/kubernetes/admin.conf
          dest: /home/ubuntu/.kube/config
          owner: ubuntu
          group: ubuntu
          mode: '600'
        become: true

      - name: copy kube config into config dir of local host
        ansible.builtin.fetch:
          src: /home/ubuntu/.kube/config
          dest: ../.kube/config
          flat: yes

      - name: generate join command
        ansible.builtin.shell: "kubeadm token create --print-join-command"
        register: join_command_output
        become: true
        changed_when: false

      - name: generate certificate key for use with join_command later
        ansible.builtin.shell: "kubeadm init phase upload-certs --upload-certs"
        register: certificate_key_output
        become: true
        changed_when: false

- hosts: all
  tasks:
    - name: save join command for other hosts to access them
      ansible.builtin.set_fact:
        join_command: "{{ hostvars[groups['controlplane'][0]]['join_command_output'].stdout }}"
        certificate_key: "{{ hostvars[groups['controlplane'][0]]['certificate_key_output'].stdout_lines[-1] }}"

- hosts: controlplane[1:]
  serial: 1
  tasks:
    - name: setup other control plane nodes
      ansible.builtin.shell:
        cmd: "{{ join_command }} --certificate-key {{ certificate_key }} --control-plane"
        creates: /etc/kubernetes/admin.conf
      become: true

    - name: copy kube config into ubuntu's home dir subfolder
      ansible.builtin.copy:
        remote_src: yes
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '600'
      become: true

- hosts: workers
  serial: 1
  tasks:
    - name: join worker nodes to the cluster
      ansible.builtin.shell:
        cmd: "{{ join_command }}"
        creates: /etc/kubernetes/pki/ca.crt
      become: true

- hosts: controlplane[0]
  gather_facts: true
  tasks:
    - name: Install Helm diff plugin
      kubernetes.core.helm_plugin:
        plugin_path: https://github.com/databus23/helm-diff
        state: present

    - name: Deploy latest version of Cilium chart inside kube-system namespace
      kubernetes.core.helm:
        name: cilium
        chart_ref: oci://quay.io/cilium/charts/cilium
        release_namespace: kube-system
        create_namespace: true
        values:
          version: 1.19.2
          hubble:
            relay:
              enabled: true
            tls:
              auto:
                enabled: true
                method: cronJob
          certgen:
            tolerations:
              - effect: NoSchedule
                key: node-role.kubernetes.io/master
                operator: Exists

    - name: Add grafana-community chart repo
      kubernetes.core.helm_repository:
        name: grafana-community
        repo_url: "https://grafana-community.github.io/helm-charts"
      no_log: true

    - name: Create a secret for Grafana admin password
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: grafana-admin-credentials
            namespace: monitoring
          type: Opaque
          stringData:
            admin-user: admin
            ldap-toml: ""
            admin-password: "{{ lookup('ansible.builtin.password', '/dev/null seed=' + inventory_hostname) }}"

    - name: Deploy latest version of Grafana chart inside monitoring namespace with values
      kubernetes.core.helm:
        name: grafana
        chart_ref: grafana-community/grafana
        release_namespace: monitoring
        create_namespace: true
        values:
          replicas: 2
          admin:
            existingSecret: "grafana-admin-credentials"
