---
- name: Check if etcd CLI exists
  ansible.builtin.stat:
    path: /home/ubuntu/.local/bin/etcdctl
  register: etcd_cli_status

- name: Install etcd CLI if not present
  when: not etcd_cli_status.stat.exists
  block:
    - name: Get latest etcd CLI version
      delegate_to: localhost
      run_once: true
      ansible.builtin.uri:
        url: https://api.github.com/repos/etcd-io/etcd/releases/latest
        return_content: true
      register: etcd_latest_stable_version

    - name: Set etcd CLI version info
      ansible.builtin.set_fact:
        etcd_cli_arch: "{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'amd64' }}"
        etcd_cli_ver: "{{ etcd_latest_stable_version.json.tag_name }}"
        etcd_cli_baseuri: "https://github.com/etcd-io/etcd/releases/download"

    - name: Get latest etcd CLI
      delegate_to: localhost
      run_once: true
      ansible.builtin.get_url:
        url: "{{ etcd_cli_baseuri }}/{{ etcd_cli_ver }}/etcd-{{ etcd_cli_ver }}-linux-{{ etcd_cli_arch }}.tar.gz"
        dest: "/tmp/etcd-linux-{{ etcd_cli_ver }}-{{ etcd_cli_arch }}.tar.gz"
        mode: '0644'

    - name: Extract etcd CLI
      ansible.builtin.unarchive:
        src: "/tmp/etcd-linux-{{ etcd_cli_ver }}-{{ etcd_cli_arch }}.tar.gz"
        dest: "/home/ubuntu/.local/opt"
        remote_src: false

    - name: Make etcd CLI executable
      ansible.builtin.file:
        path: "/home/ubuntu/.local/bin/{{ item }}"
        src: "/home/ubuntu/.local/opt/etcd-{{ etcd_cli_ver }}-linux-{{ etcd_cli_arch }}/{{ item }}"
        mode: '0755'
        state: link
      with_items:
        - etcdctl
        - etcdutl
