---
- name: Check if Cilium CLI exists
  ansible.builtin.stat:
    path: /home/ubuntu/.local/bin/cilium
  register: cilium_cli_status

- name: Install Cilium CLI if not present
  when: not cilium_cli_status.stat.exists
  block:
    - name: Get latest Cilium CLI version
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
        return_content: true
      register: cilium_latest_stable_version

    - name: Set Cilium CLI version info
      ansible.builtin.set_fact:
        cilium_cli_arch: "{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'amd64' }}"
        cilium_cli_ver: "{{ cilium_latest_stable_version.content | trim }}"
        cilium_cli_baseuri: "https://github.com/cilium/cilium-cli/releases/download"

    - name: Download Cilium CLI tarball
      delegate_to: localhost
      ansible.builtin.get_url:
        url: "{{ cilium_cli_baseuri }}/{{ cilium_cli_ver }}/cilium-linux-{{ cilium_cli_arch }}.tar.gz"
        dest: "/tmp/cilium-linux-{{ cilium_cli_ver }}-{{ cilium_cli_arch }}.tar.gz"
        checksum: "sha256:{{ cilium_cli_baseuri }}/{{ cilium_cli_ver }}/cilium-linux-{{ cilium_cli_arch }}.tar.gz.sha256sum"
        mode: '0644'

    - name: Install Cilium CLI
      ansible.builtin.unarchive:
        src: "/tmp/cilium-linux-{{ cilium_cli_ver }}-{{ cilium_cli_arch }}.tar.gz"
        dest: "/home/ubuntu/.local/bin"
        remote_src: false
