---
# tasks file for setup-node
# This will install packages and apply various system configs necessary for Kubernetes nodes.

- name: Import OS params tasks
  ansible.legacy.import_tasks: os-params.yaml

- name: Import base packages tasks
  ansible.legacy.import_tasks: packages-base.yaml

- name: Create directories in .local
  ansible.builtin.file:
    state: directory
    path: /home/ubuntu/.local/{{ item }}
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  with_items:
    - bin
    - opt

- name: Import Cilium CLI tasks
  ansible.legacy.import_tasks: install-cilium-cli.yaml

- name: Import etcd CLI tasks
  ansible.legacy.import_tasks: install-etcd-cli.yaml

- name: Import K8s packages tasks
  ansible.legacy.import_tasks: packages-k8s.yaml

- name: Import config services tasks
  ansible.legacy.import_tasks: config-services.yaml

- name: Create KubeConfig directory
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '700'
