---
# tasks file for setup-node
# This will install packages and apply various system configs necessary for Kubernetes nodes.

- name: Stop unattended-upgrades service to prevent it from running during our playbook
  ansible.builtin.systemd_service:
    name: unattended-upgrades
    state: stopped
    enabled: false
  become: true
  become_method: sudo

- name: load kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  with_items:
    - overlay
    - br_netfilter
  become: true
  become_method: sudo
  notify: Restart Server

- name: Enable ip forwarding in /proc and in the sysctl file and reload if necessary
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  become: true
  become_method: sudo

# Let iptables see bridged traffic
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
- name: Enable netfilter bridging in /proc and in the sysctl file and reload if necessary
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
  become: true
  become_method: sudo

- name: Disable swap in /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: "swap.img"
    state: absent
    backup: yes
  become: true
  become_method: sudo

- block:
  - name: add kubernetes repo key
    ansible.builtin.get_url:
      url: https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key
      dest: /etc/apt/keyrings/kubernetes-apt.asc
      mode: "0644"

  - name: add kubernetes repository
    ansible.builtin.apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt.asc] http://pkgs.k8s.io/core:/stable:/v1.34/deb/ /"
      state: present
      update_cache: yes

  - name: add helm repo key
    ansible.builtin.get_url:
      url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
      dest: /etc/apt/keyrings/helm-apt.asc
      mode: "0644"

  - name: add helm repository
    ansible.builtin.apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/helm-apt.asc] http://packages.buildkite.com/helm-linux/helm-debian/any/ any main"
      state: present
      update_cache: yes

  become: true
  become_method: sudo
  notify: Refresh apt cache

- name: trigger handlers to clean apt and reboot
  ansible.builtin.meta: flush_handlers

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - python3-pip
    - python3-kubernetes
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg
    - tree
    - containernetworking-plugins
    - ipset
    - ipvsadm
    - kubelet
    - kubeadm
    - kubectl
    - containerd
    - python-is-python3
    - helm
    update_cache: yes
    cache_valid_time: 3600  # Update if cache is older than 1 hour (3600 seconds)
  register: install_packages
  become: true
  become_method: sudo

# I ran into an issue where Ansible was working too quickly for
# ansible.builtin.dpkg_selections so let's take a 5-second nap
- name: wait 5 seconds
  ansible.builtin.pause:
    seconds: 5
  when: install_packages.changed

- name: Hold kubernetes packages at their current version
  ansible.builtin.dpkg_selections:
    name:  "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  become: true
  become_method: sudo
  ignore_errors: true

- name: enable kubelet via systemctl
  ansible.builtin.systemd_service:
    name: kubelet
    enabled: true
  become: true
  become_method: sudo

- block:
  # these two calls setup the default containerd config file
  # credit to: https://www.itzgeek.com/how-tos/linux/ubuntu-how-tos/install-containerd-on-ubuntu-22-04.html
  - name: mkdir /etc/containerd
    ansible.builtin.file:
      path: /etc/containerd
      state: directory

  - name: save default containerd config to /etc/containerd/config.toml
    ansible.builtin.shell:
      cmd: "containerd config default | tee /etc/containerd/config.toml"
      creates: /etc/containerd/config.toml

  # set CRI to use SystemdCgroup, which is false by default
  # settings take effect after restart, which is handled later
  # https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd-systemd
  - name: edit SystemdCgroup to be true in /etc/containerd/config.toml
    ansible.builtin.replace:
      path: /etc/containerd/config.toml
      regexp: 'SystemdCgroup = false'
      replace: 'SystemdCgroup = true'

  # set CRI to use SystemdCgroup, which is false by default
  # settings take effect after restart, which is handled later
  # https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd-systemd
  - name: edit SystemdCgroup to be true in /etc/containerd/config.toml
    ansible.builtin.replace:
      path: /etc/containerd/config.toml
      regexp: '^(\s*sandbox_image\s*=\s*"registry\.k8s\.io/pause):[\d\.]*"'
      replace: '\1:3.10.1"'
  become: true
  notify: Restart Containerd

- name: Create KubeConfig directory
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory

- name: Add a host to the hosts file for the control plane endpoint
  ansible.builtin.lineinfile:
    path: /etc/cloud/templates/hosts.debian.tmpl
    line: "127.0.0.1 k8s-control"
    create: true
  become: true
  become_method: sudo
  notify: Restart Server
  when:
    - "'controlplane' in groups"
    - inventory_hostname in groups['controlplane']
