---

- name: Join worker node to the cluster
  when:
    - "'workers' in groups"
    - inventory_hostname in groups['workers']
  throttle: 1
  ansible.builtin.command:
    cmd: "{{ join_command }}"
    creates: /etc/kubernetes/pki/ca.crt
  become: true

- name: Wait for all nodes to be Ready
  delegate_to: "{{ groups['controlplane'][0] }}"
  run_once: true
  kubernetes.core.k8s_info:
    kind: Node
  register: node_list
  until: >
    node_list.resources | length > 0 and
    node_list.resources | map(attribute='status.conditions') |
    map('selectattr', 'type', 'equalto', 'Ready') |
    map('map', attribute='status') | flatten | select('equalto', 'True') |
    list | length == node_list.resources | length
  retries: 20
  delay: 10
