---
argument_specs:
  main:
    short_description: Entry point for the monitoring role.
    options:
      deploy_monitoring_stack:
        type: bool
        required: false
        description: "State of the monitoring deployments."
      deploy_prometheus:
        type: bool
        required: false
        description: "Include Prometheus stack with monitoring"
