---
argument_specs:
  main:
    short_description: Entry point for the join-workers role.
    options:
      join_command:
        type: str
        required: true
        description: "The command to join the worker node to the cluster."
      certificate_key:
        type: str
        required: true
        description: "The certificate key for securely joining the worker node to the cluster."
